# -*- coding: utf-8 -*-
"""Exercicios_de_Funcao_For.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7W9xpgD4IwOW2gwimMi_ZoX22Ohy5T4

solicitar um numero inteiro positivo N ao usuario . Imprimir os numeors de N e 1. Realizar exercicio usando loops for e while
"""

#Entrada de vaiavel sera utilizada nos dois:
T = int(input("Entre com o numero inteiro maior que 1: "))
#FOR
print("For: ")

for t in range(T): # Para contador t dentro do range do numero apresentado de T faça
  print(f"{T - t}", end ="") # Mostre o calculo de T - t
print("\n")

#While

#While
T = int(input("Entre com o numero inteiro maior que 1: "))

i = 0
print("While: ") # Enquanto o contador for menor que o numero apresentado

while i < T:
  print(f"{T - t}", end"")# Mostre o calculo de T - t
  i += 1

"""Solicitar um número inteiro positivo N ao usuário. Imprimir os números de N a 1 trocando o sinal dos números. Realizar o exercício usando loops for e while. Exemplo para N igual a 5:"""

N = int(input("Digite um numero inteiro positivo: "))

print("For: ")

for n in range(N):
  print(f" {n - N}", end = "")
print("\n")

N = int(input("Digite um numero inteiro positivo: "))

print("While: ")

n = 0

while n < N:
  print(f"{ (N - n) * (-1)} ", end = "")
  n += 1

N = int(input("Digite um numero inteiro positivo: "))
#for
mult = -1
fat = 1
for n in range(N):
  num = fat * (N-n)
  fat *= mult
  print(f"{num}", end= " ")

print("\n")

#While
print("While: ")
mult = -1
fat = 1
i = 0
while i < N:
  num = fat * (N-n)
  fat *= mult
  print(f"{num}", end=" ")
  i += 1

"""solicitar um numero inteiro positico N ao usuario e inprimir i² para 0<i<N. Por exemplo para N = 5, serão impressos:

"""

N = int(input("Digite um numero inteiro positivo: "))
#for
print("For: ")
for i in range(1, N):
  print(f"{i * i}")

#While
print("While: ")

i = 1
while i < N:
  print(f"{i * i}")
  i += 1



# 5 -4 3 -2 1

N=5
mult = -1
fat = 1
for n in range(N):
  print(fat *  (N-n), end = " ")

  fat = fat * mult

# dado n inteiro imprimir i*i para 0<=i<n
"""
N = int()
N = 3
0*0 i = 0
1*1 i=1
2*2 i-2 < N
"""
print(f"   i   i*i  i**3   {i:4d} {i*i:4d} {i**3:4d}")
for i in range(N):
  print(f"{i:4d} {i*i:4d} {i**3:4d}")

M = 5
N = 4

for m in range(M):
  for n in range(N):
    print(n, end=' ')
  print()

palavra = str(input('Digite uma palavra: ')).strip().upper()
palavra_split = palavra.split()
palavra_junta = ''.join(palavra)
palavra_inverso = ''
for letra in range(len(palavra_junta) -1, -1, -1):
  palavra_inverso = palavra_inverso + palavra_junta[letra]
print(f'O inverso de {palavra_junta} é {palavra_inverso}.')
if palavra_inverso == palavra_junta:
  print('Temos um palíndromo!')
else:
  print('A frase digitada não é um palindromo')

